### ISSUE TITLE
Don't require outdated mitmproxy Version

### ISSUE THREAD

**Issue by jaykijay** [MobSF/httptools#2]
Hello,
could you please drop the hard dependency for
        'mitmproxy==5.0.1',

httptools is working fine with any recent Version like 5.1.
Maybe it's better to depend on mitmproxy >=5.0.1

If you depend on a specific mitmproxy Version distributions deploying recent mitmproxy Versions like Blackarch are getting in trouble :(

Thanks! (;

**Comment by ajinabraham** [comment]
Good point. Will change the hard pinning.
