### ISSUE TITLE
Error in setup.py causing installation error

### ISSUE THREAD

**Issue by measu** [MobSF/httptools#7]
Hello, I was trying to build MobSF from Docker file, until it fails to install `httptools`, because an error in *setup.py*.

In the 45 line of *setup.py* has a small mistake.

`mitmproxy>=6.0.0<=6.0.2`

Probably should be replace by

`mitmproxy>=6.0.0,<=6.0.2`

Have a good fix :P

**Comment by ajinabraham** [comment]
This should be fixed.
