### ISSUE TITLE
add blacklist url: 127.0.0.1:1337

### ISSUE THREAD

**Issue by ohyeah521** [MobSF/httptools#9]
Local control instructions should be added to the blacklist to exclude word count control instructions.
<img width="159" alt="2023-09-17_090736" src="https://github.com/MobSF/httptools/assets/1449374/9f7341b6-1eea-44f0-871e-4de9b4dc6831">

**Comment by ajinabraham** [comment]
This will still be captured, but we made changes to avoid killing the proxy server on repeating the traffic from httptools 5.0
